# Generated by Django 5.1.3 on 2024-12-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revistas', '0002_revista_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='revista',
            name='metadata_prefix',
            field=models.CharField(default='oai_dc', max_length=50, verbose_name='Prefijo de Metadatos'),
        ),
    ]
